services:
  php: 
    build: .
    volumes:
      - ./app:/var/www/html 
    ports: 
      - "80:80"
    networks: 
      - net

  db:
    image: mysql:latest  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD} 
    networks: 
      - net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - net

networks: 
  net:
    driver: bridge
