services:
  php: 
    build: .
    volumes:
      - ./app:/var/www/html 
    ports: 
      - "80:80"
    networks: 
      - net

  db:
    image: mysql:latest  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
    networks: 
      - net

networks: 
  net:
    driver: bridge
    