services:
  php: 
    build: .
    ports: 
      - "80:80"
    volumes:
      - ./app:/var/www/html 
  db:
    image: mysql:latest  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
    